### ISSUE TITLE
Cant build Project

### ISSUE THREAD

**Issue by llBlu** [Nithanim/cultures-multitool#5]
Hey there,
I find it quite awesome that someone actually put some effort into making a tool for this game, considering how old it is.
However when im trying to build this project (using windows 10), it throws me a error.

Error: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project lib: Fatal error compiling: java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid' -> [Help 1]

Screenshot of the console:
https://prnt.sc/vRjqmGe50J0u

Im not familiar with Maven, so i might miss something maybe.
Any ideas how to fix that?

**Comment by Nithanim** [comment]
Hello! Thank you for you interest in this weird project (and game)!

Sadly, today I have very little time but I will try to get to it tomorrow.

My best blind guess from the error message is that lombok (dependency) became incompatible with the version of java you are using. You could either try to use Java 11 which I think this program is built against. Or you could try to update the version of "org.projectlombok" to the most recent one in the `pom.xml` files. Like so:
```xml
<dependency>
    <groupId>org.projectlombok</groupId>
    <artifactId>lombok</artifactId>
    <version>1.18.30</version>
    <scope>provided</scope>
</dependency>
```
Though, this might result in problems with JavaFx (a dependency). 

I really should have documented everything a bit more, sorry! It does not help, that the project is held together by hopes and dreams :(

Thank you for telling me!

**Comment by llBlu** [comment]
This game deserves way more attention than it has, its up to this day the best game of its genre in my opinion :D

No worries about that, as it seems like you were right about the java incompatibility. Its one of my habits to download always the latest version of any software or other tools and frameworks. It turns out when i did so with java (version 21), that's where the problem was. I really should get just version 11 as you were telling about that in the description. I did now download version 11 additionally, and was successfully building your project with this version of java.

Thanks for the quick reply, and i really do appreciate that you decided to share this awesome tool of yours! After all these years, im finally able to have look at the game files and mess a bit with them :)

**Comment by Nithanim** [comment]
> This game deserves way more attention than it has, its up to this day the best game of its genre in my opinion :D

I would like to have some successor too :( But making a game is hard and time-consuming. (It's not like that I tried to start about three times...)

> [...]  java incompatibility. Its one of my habits to download always the latest version of any software or other tools and frameworks. It turns out when i did so with java (version 21) [...]

It makes sense to download the latest Java version. I mean it *is* backwards compatible (most of the time). **BUT** the problem is on the one hand lombok which uses a lot of forbidden magic but makes things easier. On the other there is the GUI framework that only states compatibility with a specific version of Java. So that makes it a bit difficult to make it work all the time. But fixing this stuff is generally just updating everything to the newest version :D

I pushed a new version that builds and starts with Java 21. Though, I do not have the game files ready to test it. (My PC is still a mess and the HDDs are not... connected). (Also the repository is a wild mess.)

> Thanks for the quick reply, and i really do appreciate that you decided to share this awesome tool of yours!

No problem! Thank you for using my tool! I am always glad that someone finds use in the stuff I make. The chance is very slim with the weird stuff I put a lot of time into for a like... non-existing audience.

> After all these years, im finally able to have look at the game files and mess a bit with them :)

There are still a lot of mysteries to solve. If you have any questions feel free to ask! Also, if you don't know how/what to contribute: knowledge is spread everywhere or just in the heads of (the remaining) people (me?). Asking the right questions and writing that down in some "central" public space is highly appreciated I think.

(Even using the "Multitool" is not very logical.)
